name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x

    - name: Build and Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.gh_pages }}
        BASE_BRANCH: master 
        BRANCH: gh-pages 
        FOLDER: storybook-static 
      run: |
        npm ci
        npm run deploy
