name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: IvanCybercom/play@master
      env:
        ACCESS_TOKEN: ${{ secrets.gh_pages }}
        BASE_BRANCH: master 
        BRANCH: gh-pages 
        FOLDER: build 
        BUILD_SCRIPT: npm ci && npm run deploy 
